# Cổng chạy server (truy cập localhost:8080)
server.port=8080

# --- KẾT NỐI SQL SERVER ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=phoneSale;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- CẤU HÌNH JPA (HIBERNATE) ---
# update: tự động cập nhật bảng nếu code Java thay đổi (không xóa dữ liệu cũ)
spring.jpa.hibernate.ddl-auto=update
# Hiện câu lệnh SQL trong Console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

## --- CẤU HÌNH JWT (TOKEN) ---
#app.jwtSecret=DayLaKhoaBiMatRatDaiDeMaHoaTokenChoDuAnBanDienThoaiJavaSpring2025
#app.jwtExpirationMs=86400000